name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ci
  cancel-in-progress: true

jobs:
  nixfmt:
    name: nixfmt
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30

      - name: nixfmt
        run: nix run nixpkgs#nixfmt-rfc-style -- --check .

  deadnix:
    name: deadnix
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30

      - name: deadnix
        run: nix run nixpkgs#deadnix -- --fail .

  gitleaks:
    name: gitleaks
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30

      - name: gitleaks
        run: nix run nixpkgs#gitleaks -- detect --no-git --source=. --verbose --redact --exit-code 1
